# Generated by Django 5.2.1 on 2025-05-30 05:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_identifier', models.CharField(blank=True)),
                ('document_type', models.CharField(blank=True)),
                ('vat_rate', models.CharField(blank=True)),
                ('nds_activ', models.CharField(blank=True)),
                ('currency', models.CharField(blank=True)),
                ('form_format', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_advance', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
                ('inn', models.CharField(blank=True)),
                ('kpp', models.CharField(blank=True)),
                ('address', models.CharField(blank=True)),
                ('manager', models.CharField(blank=True)),
                ('manager_fio', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('inn', models.CharField(blank=True)),
                ('kpp', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('inn', models.CharField(blank=True)),
                ('kpp', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(blank=True)),
                ('transportation_data', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_adjusted', models.BooleanField(blank=True, default=False)),
                ('adjusted_number', models.CharField(blank=True)),
                ('adjusted_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutputSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_stamp', models.BooleanField(blank=True)),
                ('show_signature', models.BooleanField(blank=True)),
                ('file_format', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('other', models.CharField(blank=True)),
                ('resp_position', models.CharField(blank=True)),
                ('resp_name', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('full_name', models.CharField(blank=True)),
                ('inn', models.CharField(blank=True)),
                ('kpp', models.CharField(blank=True)),
                ('reg_address', models.CharField(blank=True)),
                ('address', models.CharField(blank=True)),
                ('requisite', models.CharField(blank=True)),
                ('manager', models.CharField(blank=True)),
                ('manager_fio', models.CharField(blank=True)),
                ('accountant_fio', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
                ('number', models.CharField(blank=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_signed', models.BooleanField(blank=True)),
                ('other', models.CharField(blank=True)),
                ('resp_position', models.CharField(blank=True)),
                ('resp_name', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('inn', models.CharField(blank=True)),
                ('kpp', models.CharField(blank=True)),
                ('address', models.CharField(blank=True)),
                ('manager_fio', models.CharField(blank=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upd.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('article', models.CharField(blank=True)),
                ('unit', models.CharField(blank=True)),
                ('quantity', models.CharField(blank=True)),
                ('customs_code', models.CharField(blank=True)),
                ('customs_type_code', models.CharField(blank=True)),
                ('excise_duty', models.CharField(blank=True)),
                ('number', models.CharField(blank=True, default=1)),
                ('country_code', models.CharField(blank=True)),
                ('country_name', models.CharField(blank=True)),
                ('full_sum', models.FloatField(blank=True, default=0.0)),
                ('customs_declaration_num', models.TextField(blank=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upd.section')),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True)),
                ('name', models.CharField(blank=True)),
                ('inn', models.CharField(blank=True)),
                ('kpp', models.CharField(blank=True)),
                ('address', models.CharField(blank=True)),
                ('manager_fio', models.CharField(blank=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upd.seller')),
            ],
        ),
    ]
