# Generated by Django 5.2.1 on 2025-05-30 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_sum',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upd.section'),
        ),
    ]
